package com.ssl.bluetruth.servlet.receiver;

public enum Message {

    MESSAGECODE001("001", MessageCategory.WARNING, "Exception Retrieving MAC Address", "Device ID and InStation credentials can not be generated."),
    MESSAGECODE01A("01a", MessageCategory.CRITICAL, "Exception Retrieving MAC Address", "Device ID and InStation credentials can not be generated."),
    MESSAGECODE002("002", MessageCategory.WARNING, "Exception Retrieving MAC Address", "Unspecified MAC address retrieval error. OutStation will exit."),
    MESSAGECODE003("003", MessageCategory.WARNING, "Exception Reading Settings", "Settings file status flag after OutStation start is false (so only after a power off/on) cycle. Error retrieving settings file. GPRS may be temporarily down. OutStation will loop and try again."),
    MESSAGECODE004("004", MessageCategory.CRITICAL, "Exception On Outstation Start", "General exception in main module load. OutStation will continue."),
    MESSAGECODE04A("004a", MessageCategory.WARNING, "Error Detecting Devices In Journey Time Mode", "OutStation will reset and continue."),
    MESSAGECODE04B("004b", MessageCategory.WARNING, "Error Detecting Devices QD Mode (V2 Only)", "OutStation will reset and continue."),
    MESSAGECODE04C("004c", MessageCategory.WARNING, "Error Detecting Devices, Mode Unknown, Default To Journey Time Mode", "OutStation will reset and continue in journey time mode."),
    MESSAGECODE04D("004d", MessageCategory.WARNING, "Information Idle Mode Selected", "Idle mode is selected. No device discovery just error reporting."),
    MESSAGECODE04E("004e", MessageCategory.WARNING, "Error Detecting Devices, Mode Unknown, Default To Journey Time Mode", "OutStation will reset and continue in journey time mode."),
    MESSAGECODE04F("004f", MessageCategory.WARNING, "Error Uploading Logs", "OutStation will continue without uploading logs. Will retry on next inquiry cycle if settings file entry for upload error logs set to 1."),
    MESSAGECODE04G("004g", MessageCategory.WARNING, "Error Detecting Devices In Default Journey Time Mode", "OutStation will reset and continue in journey time mode."),
    MESSAGECODE04H("004h", MessageCategory.WARNING, "Error Detecting Devices, Default Unknown, Default To Journey Time Mode", "OutStation will reset and continue in journey time mode."),
    MESSAGECODE04I("004i", MessageCategory.WARNING, "Error Detecting Devices, Mode Unknown, Default To Journey Time Mode", "OutStation will reset and continue in journey time mode."),
    MESSAGECODE04J("004j", MessageCategory.WARNING, "Operation Mode Setting Not Recognised", "OutStation will reset and continue in journey time mode."),
    MESSAGECODE005("005", MessageCategory.INFORMATION, "Reading Settings On Retry Ok", "Settings file received with no errors after retries."),
    MESSAGECODE05A("05a", MessageCategory.CRITICAL, "Error Default Settings Files Does Not Exist", "OutStation will continue with original manufactures settings if possible. However the OutStation may have incorrect Url information and cannot retrieve its settings from the correct InStation. "),
    MESSAGECODE05B("05b", MessageCategory.CRITICAL, "Error Reading Default Settings File", "OutStation will continue with original manufactures settings if possible. However the OutStation may have incorrect Url information and cannot retrieve its settings from the correct InStation."),
    MESSAGECODE006("006", MessageCategory.WARNING, "Exception Reading Settings", "Settings file format exception. Check the settings file syntax carefully. OutStation will continue with current settings."),
    MESSAGECODE06A("06a", MessageCategory.WARNING, "Exception Reading Default Settings", "Settings file format exception. Check the settings file syntax carefully. OutStation will continue with current settings."),
    MESSAGECODE007("007", MessageCategory.WARNING, "Exception Reading Settings", "Setting not recognised in settings file. Check the settings file syntax carefully. OutStation will continue with current settings. Check for 096 errors which may point to poor communications."),
    MESSAGECODE07A("07a", MessageCategory.WARNING, "Unrecognised Entries In Default Settings File", "Setting not recognised in settings file. Check the settings file syntax carefully. OutStation will continue with current settings."),
    MESSAGECODE008("008", MessageCategory.WARNING, "Exception Reading Settings", "Settings file contains a line without a name value pair. Check the settings file syntax carefully. OutStation will continue with current settings."),
    MESSAGECODE08A("08a", MessageCategory.WARNING, "Exception Reading Default Settings", "Settings file contains a line without a name value pair. Check the settings file syntax carefully. OutStation will continue with current settings."),
    MESSAGECODE009("009", MessageCategory.WARNING, "Exception Reading Settings", "General exception. OutStation will continue using the previous saved settings if possible."),
    MESSAGECODE010("010", MessageCategory.INFORMATION, "Form Load Successful", "Confirmation that OutStation has started ok. Not an error."),
    MESSAGECODE011("011", MessageCategory.WARNING, "Http Send Alert Start Message Exception. V2 Only", "Failed to send alert start after a number of attempts. OutStation continues in old alert condition. Next inquiry cycle will test for alert again."),
    MESSAGECODE012("012", MessageCategory.INFORMATION, "Success Sending Alert Clear Message. V2 Only", "No error, confirmation of alert clear message sent."),
    MESSAGECODE013("013", MessageCategory.INFORMATION, "Success Sending Alert Start Message. V2 Only", "No error, confirmation of alert start message sent."),
    MESSAGECODE014("014", MessageCategory.INFORMATION, "Success Sending Summary Message. V2 Only", "No error, confirmation of summary message sent."),
    MESSAGECODE016("016", MessageCategory.WARNING, "Exception From Detected Device Hash Operation", "BT non phone device MAC failed hash. OutStation will continue. Journey matching may be affected."),
    MESSAGECODE017("017", MessageCategory.WARNING, "Exception From Detected Device Hash Operation", "BT non phone device MAC failed hash amendments. OutStation will continue. Journey matching may be affected."),
    MESSAGECODE018("018", MessageCategory.WARNING, "Exception From Detected Device Hash Operation", "BT phone device MAC failed hash. OutStation will continue. Journey matching may be affected."),
    MESSAGECODE019("019", MessageCategory.WARNING, "Exception From Detected Device Hash Operation", "BT phone device MAC failed hash amendments. OutStation will continue. Journey matching may be affected."),
    MESSAGECODE020("020", MessageCategory.WARNING, "Exception From Detected Device Hash Operation", "General hashing error. OutStation will continue. Journey matching may be affected."),
    MESSAGECODE020A("020a", MessageCategory.WARNING, "Exception From Hash Operation", "General hashing error. OutStation will continue. Journey matching may be affected."),
    MESSAGECODE021("021", MessageCategory.WARNING, "Exception From Speed Category Operation, V2 Only", "Error creating very slow speed. Will affect alert and heart beat vehicle count category."),
    MESSAGECODE022("022", MessageCategory.WARNING, "Exception From Speed Category Operation, V2 Only", "Error creating slow speed category. Will affect alert and heart beat vehicle count."),
    MESSAGECODE023("023", MessageCategory.WARNING, "Exception From Speed Category Operation, V2 Only", "Error creating moderate speed category. Will affect alert and heart beat vehicle count."),
    MESSAGECODE024("024", MessageCategory.WARNING, "Exception From Speed Category Operation, V2 Only", "Error creating free speed category. Will affect alert and heart beat vehicle count."),
    MESSAGECODE025("025", MessageCategory.WARNING, "Exception From Speed Category Operation, V2 Only", "Error deleting static devices no longer current. Will affect detected vehicle count."),
    MESSAGECODE026("026", MessageCategory.WARNING, "Exception From Speed Category Operation, V2 Only", "Error deleting very slow speed devices no longer current. Will affect detected vehicle count."),
    MESSAGECODE027("027", MessageCategory.WARNING, "Exception From Speed Category Operation, V2 Only", "Error deleting slow speed devices no longer current. Will affect detected vehicle count."),
    MESSAGECODE028("028", MessageCategory.WARNING, "Exception From Speed Category Operation, V2 Only", "Error deleting moderate speed devices no longer current. Will affect detected vehicle count."),
    MESSAGECODE029("029", MessageCategory.WARNING, "Exception From Speed Category Operation, V2 Only", "Error deleting free speed devices no longer current. Will affect detected vehicle count."),
    MESSAGECODE030("030", MessageCategory.WARNING, "Exception From Hash Operation, V2 Only", "Error adding detected signatures to speed categories. Will affect detected vehicle counts."),
    MESSAGECODE031("031", MessageCategory.CRITICAL, "Exception Building Query String", "Failed to build message. All messages affected."),
    MESSAGECODE032("032", MessageCategory.CRITICAL, "Http Alert Stop Exception, V2 Only", "Failed to send alert clear after a number of attempts. OutStation continues."),
    MESSAGECODE033("033", MessageCategory.CRITICAL, "Http Failed Read Exceptions", "More than 5 exceptions when trying to read settings file over http. Trailing value is the number or retries so far."),
    MESSAGECODE033A("033a", MessageCategory.CRITICAL, "Http Failed Read Exceptions", "More than 5 exceptions when trying to read settings file over http. Trailing value is the number or retries so far."),
    MESSAGECODE034("034", MessageCategory.WARNING, "Read Status File Content Error", "OutStation will continue but status not recovered, OutStation will reboot without previous status or state considered."),
    MESSAGECODE035("035", MessageCategory.CRITICAL, "Blue Tooth Cycle General Exception", "OutStation will reset. May not detect any devices."),
    MESSAGECODE036("036", MessageCategory.WARNING, "Unrecognised State File Entry", "OutStation will continue but state not recovered, OutStation will reboot without previous state considered."),
    MESSAGECODE037("037", MessageCategory.WARNING, "Zero Length State File Entry", "OutStation will continue but state not recovered, OutStation will reboot without previous state considered."),
    MESSAGECODE038("038", MessageCategory.WARNING, "Read State File, Unknown Entry", "OutStation will continue but state not recovered, OutStation will reboot without previous state considered."),
    MESSAGECODE039("039", MessageCategory.WARNING, "Read State File, Entry Contain Short Lines", "OutStation will continue but state not recovered, OutStation will reboot without previous state considered."),
    MESSAGECODE040("040", MessageCategory.WARNING, "General Exception State File Select", "OutStation will continue but state not recovered, OutStation will reboot without previous state considered."),
    MESSAGECODE041("041", MessageCategory.WARNING, "Read State File, General Exception Reading State File", "OutStation will continue but state not recovered, OutStation will reboot without previous state considered."),
    MESSAGECODE042("042", MessageCategory.WARNING, "Exception Deleting Log File", "Log file not deleted. If error continues disk will eventually fill up and OutStation will stop."),
    MESSAGECODE043("043", MessageCategory.WARNING, "Read State File, Read Error", "OutStation will continue but state not recovered, OutStation will reboot without previous state considered."),
    MESSAGECODE043A("043a", MessageCategory.WARNING, "Error Saving To Or Creating A New Log File", "OutStation will continue but might have a log file."),
    MESSAGECODE044("044", MessageCategory.WARNING, "Unrecognised Entry In Settings File", "One of the lines in the settings file does not contain a valid entry for a name value pair. There is no value on one side or the pair. Check the settings syntax. The OutStation trapped the error and will continue."),
    MESSAGECODE044A("044a", MessageCategory.WARNING, "Unrecognised Entry In Settings File", "One of the lines in the settings file does not contain a valid entry for a name value pair. There is no value on one side or the pair. Check the settings syntax. The OutStation trapped the error and will continue."),
    MESSAGECODE045("045", MessageCategory.WARNING, "Reading State On Reset Error", "OutStation will continue but state not recovered, OutStation will reboot without previous state considered."),
    MESSAGECODE046("046", MessageCategory.WARNING, "Reading State On Reset Error", "OutStation will continue but state not recovered, OutStation will reboot without previous state considered."),
    MESSAGECODE047("047", MessageCategory.WARNING, "Hash Device Address Error", "OutStation loops to next discovery cycle."),
    MESSAGECODE047B("047b", MessageCategory.WARNING, "Hash Device Address Error", "OutStation loops to next discovery cycle."),
    MESSAGECODE048("048", MessageCategory.WARNING, "Hash Device Address Error", "OutStation loops to next discovery cycle."),
    MESSAGECODE049("049", MessageCategory.WARNING, "Retrieving Device Name Exception", "InStation credentials can not be generated."),
    MESSAGECODE049A("049a", MessageCategory.WARNING, "Retrieving Device Name Exception", "InStation credentials can not be generated."),
    MESSAGECODE049B("049b", MessageCategory.WARNING, "Retrieving Device Name Exception", "InStation credentials can not be generated."),
    MESSAGECODE049C("049c", MessageCategory.WARNING, "Retrieving Device Name Exception", "InStation credentials can not be generated."),
    MESSAGECODE050("050", MessageCategory.WARNING, "Upload Heart Beat And Summary Count Exception, V2 Only", "Error returned from http web request when uploading heart beat and summary count data."),
    MESSAGECODE052C("052c", MessageCategory.WARNING, "Error Building Occupancy Data, V2 Only", "OutStation will continue. This data will be abandoned."),
    MESSAGECODE052("052", MessageCategory.WARNING, "Hex Conversion Exception", "With phones count values will be affected."),
    MESSAGECODE053("053", MessageCategory.WARNING, "Hex Conversion Exception", "With phones count values will be affected."),
    MESSAGECODE054("054", MessageCategory.WARNING, "Error Parsing Settings", "Settings file read has aborted, unknown error, OutStation will ignore the error and retry on next settings file get time."),
    MESSAGECODE054A("054a", MessageCategory.WARNING, "Error Parsing Default Settings", "Settings file read has aborted, unknown error, OutStation will ignore the error and retry on next settings file get time."),
    MESSAGECODE055("055", MessageCategory.WARNING, "Lines In Settings File Are Too Short To Be A Value", "OutStation will ignore the error and continue. Check syntax of settings data."),
    MESSAGECODE055A("055a", MessageCategory.WARNING, "Lines In Settings File Are Too Short To Be A Value", "OutStation will ignore the error and continue. Check syntax of settings data."),
    MESSAGECODE057("057", MessageCategory.WARNING, "Error Reading A Line Of The Settings Downloaded From Server", "Settings data contains a null. Check syntax of settings data. OutStation continues."),
    MESSAGECODE058("058", MessageCategory.CRITICAL, "Web Response Return Status Code Was Not 200", "Http exchange did not succeed."),
    MESSAGECODE059("059", MessageCategory.WARNING, "General Exception Downloading Settings File", "General exception. OutStation will continue."),
    MESSAGECODE060("060", MessageCategory.WARNING, "Error Converting Count Values From Decimal To Hex", "OutStation will continue."),
    MESSAGECODE061A("061a", MessageCategory.WARNING, "Hash Error", "Value of FFFF is used OutStation continues."),
    MESSAGECODE061B("061b", MessageCategory.WARNING, "Hash Error", "Value of FFFF is used OutStation continues."),
    MESSAGECODE062A("062a", MessageCategory.WARNING, "Hash Error", "Value of FFFF is used OutStation continues."),
    MESSAGECODE062B("062b", MessageCategory.WARNING, "Hash Error", "Value of FFFF is used OutStation continues."),
    MESSAGECODE063("063", MessageCategory.WARNING, "Collect Settings Failed", "General exception returned from http. OutStation will continue using previously saved settings. Check data and messages are being received."),
    MESSAGECODE064("064", MessageCategory.WARNING, "Checking Of Collected Settings Failed", "Received settings contain unknown values. The settings are rejected; OutStation continues to use previous settings. OutStation will continue."),
    MESSAGECODE064A("064a", MessageCategory.WARNING, "Reading Default Settings From Local Disk Failed", "Settings contain unknown values. OutStation will continue."),
    MESSAGECODE064B("064b", MessageCategory.WARNING, "Error Saving To Log File", "OutStation will continue. Log file is not current."),
    MESSAGECODE065("065", MessageCategory.INFORMATION, "Empty Road Reset", "Whilst road is empty OutStation does housekeeping including a reset."),
    MESSAGECODE066("066", MessageCategory.WARNING, "Upload Scan Inquiry Results Failed", "General exception. OutStation will continue as Communications or InStation may be experiencing problems."),
    MESSAGECODE067A("067a", MessageCategory.WARNING, "Error Downloading Settings File", "Http error when downloading settings file, returned string is incorrect."),
    MESSAGECODE067B("067b", MessageCategory.WARNING, "Error Downloading Settings File", "Http error when downloading settings file, response from InStation incorrect."),
    MESSAGECODE067C("067c", MessageCategory.WARNING, "Error Downloading Settings File", "Http error when downloading settings file, return string is either nothing or 1 char."),
    MESSAGECODE068A("068a", MessageCategory.WARNING, "Error Uploading Scan Data", "Http error when uploading scan data, return string is incorrect."),
    MESSAGECODE068B("068b", MessageCategory.WARNING, "Error Uploading Scan Data", "Http error when uploading scan data, return string is incorrect."),
    MESSAGECODE069("069", MessageCategory.WARNING, "Error Uploading Scan Data", "General web exception."),
    MESSAGECODE070A("070a", MessageCategory.WARNING, "Error Returned From Reset Device", "OutStation has not reset. If error is persistent OutStation housekeeping will be minimal and eventually OutStation will stop."),
    MESSAGECODE070B("070b", MessageCategory.WARNING, "Error Returned From Reset Device", "Failed to write application state to disk before rest. OutStation will reset but without current state. "),
    MESSAGECODE070C("070c", MessageCategory.WARNING, "Error Returned From Reset Device", "Failed to write application state to disk before rest. OutStation will reset but without current state."),
    MESSAGECODE071("071", MessageCategory.INFORMATION, "Not An Error But Informational; Rebooting Now", "Either the OutStation housekeeping time is now or the settings file settings has been set to 1."),
    MESSAGECODE072("072", MessageCategory.WARNING, "Error Uploading Heart Beat Status And Count. V2 Only.", "Error returned from InStation. Heart beat may not have been received by InStation."),
    MESSAGECODE072A("072a", MessageCategory.WARNING, "Error Uploading Buffered Messages", "Error returned from InStation. Buffered data may not have been received at InStation."),
    MESSAGECODE072B("072b", MessageCategory.WARNING, "Error, Message Entry In Buffered Message File Isn't Recognised", "Error returned by OutStation. OutStation will continue but buffered messages will not include the unrecognised entry."),
    MESSAGECODE072C("072c", MessageCategory.INFORMATION, "Uploaded Buffered Messages", "Indicates that a buffered message upload was successfully completed."),
    MESSAGECODE072D("072d", MessageCategory.INFORMATION, "Uploaded Buffered Messages", "Indicates that a buffered message upload was successfully completed."),
    MESSAGECODE072E("072e", MessageCategory.WARNING, "Error Uploading Buffered Messages", "Error returned from InStation. Buffered data may not have been received at InStation."),
    MESSAGECODE073("073", MessageCategory.WARNING, "Error Returned From Alert Clear Upload, V2 Only.", "Return status from InStation was incorrect; alert clear may not have been received by InStation. If problem persists it should be considered critical."),
    MESSAGECODE074("074", MessageCategory.CRITICAL, "Error Returned From Alert Start Upload, V2 Only.", "Return status from InStation was incorrect; alert start may not have been received by InStation. If problem persists it should be considered critical."),
    MESSAGECODE075A("075a", MessageCategory.WARNING, "Device Hashed Mac Address Failed To Count", "This device address is dropped and OutStation continues."),
    MESSAGECODE075B("075b", MessageCategory.WARNING, "Device Hashed Mac Address Failed To Count", "This device address is dropped and OutStation continues."),
    MESSAGECODE075C("075c", MessageCategory.WARNING, "Device Hashed Mac Address Failed To Count", "This device address is dropped and OutStation continues."),
    MESSAGECODE075D("075d", MessageCategory.WARNING, "Device Hashed Mac Address Failed To Count", "This device address is dropped and OutStation continues."),
    MESSAGECODE075E("075e", MessageCategory.WARNING, "Device Hashed Mac Address Failed To Count", "This device address is dropped and OutStation continues."),
    MESSAGECODE076("076", MessageCategory.WARNING, "Error Writing Alert State Message To File", "Following housekeeping the OutStation may not return in the correct alert condition."),
    MESSAGECODE076A("076a", MessageCategory.WARNING, "Error Writing Alert State Message To File", "Following housekeeping the OutStation may not return in the correct alert condition."),
    MESSAGECODE076B("076b", MessageCategory.WARNING, "Error Appending Reset Status Message To Status File", "Following housekeeping the OutStation may not return in the correct alert condition."),
    MESSAGECODE076D("076d", MessageCategory.WARNING, "Error Saving Outstation State File", "OutStation will continue but OutStation will assume a manual power off and then on."),
    MESSAGECODE076E("076e", MessageCategory.WARNING, "Error Appending Reset Status Message To Status File", "Following housekeeping the OutStation may not return in the correct alert condition. OutStation will continue but OutStation will assume a manual power off and on."),
    MESSAGECODE077("077", MessageCategory.WARNING, "Error Writing Alert State Message To File", "Following housekeeping the OutStation may not return in the correct alert condition."),
    MESSAGECODE079AB("079ab", MessageCategory.WARNING, "Error Reading Alert State File", "Alert state not saved. OutStation will continue but alert clear will be assumed."),
    MESSAGECODE079BB("079bb", MessageCategory.WARNING, "Error Reading Alert State File", "Alert state not saved. OutStation will continue but alert clear will be assumed."),
    MESSAGECODE079CB("079cb", MessageCategory.WARNING, "Error Reading Alert State File", "Alert state not saved. OutStation will continue but alert clear will be assumed."),
    MESSAGECODE079DB("079db", MessageCategory.WARNING, "Error Reading Alert State File", "Alert state not saved. OutStation will continue but alert clear will be assumed."),
    MESSAGECODE079A("079a", MessageCategory.WARNING, "Error Reading Settings File", "Nothing or zero length string read from file. Following maintenance at midnight the OutStation may not return in the correct alert condition."),
    MESSAGECODE079B("079b", MessageCategory.WARNING, "Error Reading Settings File", "Error reading file. Following maintenance at midnight the OutStation may not return in the correct alert condition."),
    MESSAGECODE079C("079c", MessageCategory.OK, "Status File Does Not Exist. This Is Not An Error. V2 Only", "OutStation has not reached the first alert start, stop or heart beat message."),
    MESSAGECODE079D("079d", MessageCategory.WARNING, "Error Reading Settings File", "General error catch. If settings have not changed then the OutStation will continue without change using the previously saved settings from OutStation or failing that the default settings on local disk."),
    MESSAGECODE080("080", MessageCategory.CRITICAL, "Error Creating Heart Beat Query String, V2 Only.", "OutStation can't continue, client id and date time corrupt."),
    MESSAGECODE080A("080a", MessageCategory.INFORMATION, "Outstation Sensed TCPIP Socket Slow And Changed Socket.", "OutStation has switched to new Bluetooth client. OutStation will continue."),
    MESSAGECODE080B("080b", MessageCategory.WARNING, "Error Completing Device Discovery And Sending Data", "OutStation will loop and try again."),
    MESSAGECODE080C("080c", MessageCategory.INFORMATION, "Error Creating Heart Beat Query String", "OutStation will continue but the heart beat date time may be incorrect."),
    MESSAGECODE082("082", MessageCategory.WARNING, "Discover Devices Has Returned And Error", "Background discovery error in blue tooth module. If it persists the system will loop with no device discovery."),
    MESSAGECODE082B("082b", MessageCategory.WARNING, "Read State File Error", "Can't retrieve state file. If in QD mode this may be critical. In JT mode it isn't critical."),
    MESSAGECODE083("083", MessageCategory.WARNING, "Alert Condition Error", "An alert hysteresis condition outside of the expected has occurred. OutStation will continue but alerts may be generated more frequently than expected."),
    MESSAGECODE084("084", MessageCategory.WARNING, "Upload Error String Error Reported In Idle Mode, V2 Only.", "OutStation failed to upload error."),
    MESSAGECODE084A("084a", MessageCategory.WARNING, "Upload Error Summary Info Error", "OutStation failed to upload error summary information. "),
    MESSAGECODE084B("084b", MessageCategory.WARNING, "Unrecognised Mode Setting", "Check settings file mode setting."),
    MESSAGECODE085A("085a", MessageCategory.WARNING, "Error Saving Settings File", "General exception: OutStation failed to save settings file. Changes to settings may not be possible. OutStation may default to local default settings."),
    MESSAGECODE085B("085b", MessageCategory.WARNING, "Error Saving Settings File", "OutStation failed to save settings file. Changes to settings may not be possible. OutStation may default to local default settings."),
    MESSAGECODE085C("085c", MessageCategory.WARNING, "Error Saving Settings File", "OutStation failed to save settings file. Changes to settings may not be possible. OutStation may default to local default settings."),
    MESSAGECODE086("086", MessageCategory.WARNING, "Error Retrieving Settings File In Retry Loop", "General exception error; OutStation will continue but with settings read from local disk."),
    MESSAGECODE087("087", MessageCategory.WARNING, "Error Saving Buffered Messages", "OutStation failed to save buffered message. Data is lost."),
    MESSAGECODE087A("087a", MessageCategory.WARNING, "Error Writing Buffered Messages", "OutStation failed to save buffered message. Data is lost."),
    MESSAGECODE088A("088a", MessageCategory.WARNING, "Error Reading Buffered Message File", "OutStation failed to read buffered message."),
    MESSAGECODE088B("088b", MessageCategory.WARNING, "Error Reading Buffered Message File", "OutStation failed to read buffered message."),
    MESSAGECODE088C("088c", MessageCategory.INFORMATION, "Not An Error, Buffered Messages Is Empty", "There are no buffered messages to send."),
    MESSAGECODE088D("088d", MessageCategory.WARNING, "Error Reading Buffered Message File", "OutStation failed to read buffered message."),
    MESSAGECODE089A("089a", MessageCategory.WARNING, "Error Finding Average Value For Smoothing", "OutStation failed evaluate an average value smoothing will not occur."),
    MESSAGECODE089B("089b", MessageCategory.WARNING, "Error Finding Average Value For Smoothing ", "OutStation failed evaluate an average value smoothing will not occur."),
    MESSAGECODE089C("089c", MessageCategory.WARNING, "Error Implementing Smoothing ", "General exception from smoothing block, OutStation failed to implement smoothing."),
    MESSAGECODE090("090", MessageCategory.INFORMATION, "Smoothing Applied", "OutStation has applied a smoothing value."),
    MESSAGECODE091("091", MessageCategory.WARNING, "Error Uploading Error String And Status, V2 Only.", "Failed to upload error string and count status information."),
    MESSAGECODE091A("091a", MessageCategory.WARNING, "Error Uploading Error String And Status", "Failed to upload error string and count status information."),
    MESSAGECODE092A("092a", MessageCategory.WARNING, "Error Adding Detected Device Counts To Discovered Devices Query String", "OutStation will loop to next inquiry cycle. This data is lost."),
    MESSAGECODE092B("092b", MessageCategory.WARNING, "Generic Error Building Debug Query String", "OutStation will continue without uploading debug information."),
    MESSAGECODE093("093", MessageCategory.WARNING, "Error Saving Clear Messages To Buffer, V2 Only.", "OutStation will continue but unsent clear messages are not buffered. Alert condition may be incorrect."),
    MESSAGECODE094("094", MessageCategory.WARNING, "Error Saving Heart Beat Messages To Buffer, V2 Only.", "OutStation will continue but unsent heart beat messages are not buffered."),
    MESSAGECODE095("095", MessageCategory.WARNING, "Error Saving Alert Start Messages To Buffer", "OutStation will continue but unsent alert start messages are not buffered. Alert condition may be incorrect."),
    MESSAGECODE096("096", MessageCategory.WARNING, "Error Saving Error String Messages To Buffer", "OutStation will continue; unsent messages may not be buffered."),
    MESSAGECODE096A("096a", MessageCategory.WARNING, "Error Saving Error String Messages To Buffer", "OutStation will continue but unsent error string messages are not buffered."),
    MESSAGECODE096B("096b", MessageCategory.WARNING, "Error Saving Error String Messages To Buffer", "General exception. OutStation will continue but unsent error string messages are not buffered."),
    MESSAGECODE096D("096d", MessageCategory.WARNING, "Error Saving Error String Messages To Buffer", "OutStation will continue but unsent error string messages are not buffered."),
    MESSAGECODE096E("096e", MessageCategory.WARNING, "Error Saving Error String Messages To Buffer", "OutStation will continue but unsent error string messages are not buffered."),
    MESSAGECODE096F("096f", MessageCategory.WARNING, "Error Uploading Journey Time Scan Data", "OutStation will continue and try again. Message will be buffered."),
    MESSAGECODE097("097", MessageCategory.WARNING, "Error Completing Ping Test", "OutStation will continue but without effective network pre testing."),
    MESSAGECODE098("098", MessageCategory.WARNING, "Error Uploading Buffered Messages", "General error uploading data. OutStation will continue. Unsent data may not be buffered."),
    MESSAGECODE099("099", MessageCategory.WARNING, "Error Deleting Buffer Message File", "OutStation will continue."),
    MESSAGECODE100("100", MessageCategory.WARNING, "General Exception When Overwriting Old Buffer Message File With Unsent Messages", "OutStation will continue but buffering may not be available."),
    MESSAGECODE100A("100a", MessageCategory.WARNING, "General Exception When Clearing Old Buffer Message File ", "Failed to clear buffered message file. OutStation will continue but buffering may not be available."),
    MESSAGECODE100B("100b", MessageCategory.INFORMATION, "Error When Reading The Buffered Message File", "OutStation will continue but without sending buffered messages."),
    MESSAGECODE100C("100c", MessageCategory.WARNING, "General Error When Reading The Buffered Message File", "OutStation will continue but without sending buffered messages."),
    MESSAGECODE101("101", MessageCategory.WARNING, "Error Creating Upload Error String In Idle Mode, V2 Only.", "OutStation will abort this operation and continue."),
    MESSAGECODE101A("101a", MessageCategory.WARNING, "Error Creating Upload Error String In Journey Time Mode", "OutStation will abort this operation and continue."),
    MESSAGECODE107("107", MessageCategory.WARNING, "Error Returning Local Blue Tooth Radio Address", "OutStation can't set up Bluetooth PIN for this device. OutStation will continue but access to the OutStation over its Bluetooth connection is not protected."),
    MESSAGECODE107A("107a", MessageCategory.WARNING, "Error Returning Local Blue Tooth Radio Address", "OutStation can't set up Bluetooth PIN for this device. OutStation will continue but access to the OutStation over its Bluetooth connection is not protected"),
    MESSAGECODE108("108", MessageCategory.WARNING, "Error From Hash Devices", "OutStation will exit journey time mode and rest itself to try again"),
    MESSAGECODE108B("108b", MessageCategory.WARNING, "Error From Hash Devices", "OutStation will exit journey time mode and rest itself to try again"),
    MESSAGECODE109("109", MessageCategory.WARNING, "Error From Amending Hash Devices", "OutStation will continue to next hash next device"),
    MESSAGECODE110A("110a", MessageCategory.WARNING, "Error Creating Journey Time Payload Info", "OutStation will continue to next inquiry cycle"),
    MESSAGECODE110B("110b", MessageCategory.WARNING, "Error Sending Journey Time Payload Info", "OutStation will continue to next inquiry cycle"),
    MESSAGECODE110C("110c", MessageCategory.WARNING, "Error Saving Buffered Message", "OutStation will continue without buffered message"),
    MESSAGECODE110D("110d", MessageCategory.WARNING, "Generic Error Building And Sending Journey Time Info", "OutStation will continue to next inquiry cycle"),
    MESSAGECODE111("111", MessageCategory.WARNING, "Failed To Retrieve Settings From Instation", "OutStation will use last saved set and continue if possible"),
    MESSAGECODE112("112", MessageCategory.WARNING, "Failed To Upload Errors At The End Of A Journey Time Cycle", "OutStation will continue to next journey time cycle");

    private final String code;
    private final MessageCategory category;
    private final String description;
    private final String descriptionDetail;

    private Message(String code, MessageCategory category, String description, String descriptionDetail) {
        this.code = code;
        this.category = category;
        this.description = description;
        this.descriptionDetail = descriptionDetail;
    }

    public static Message getByCode(String code) {
        for (Message message : Message.values()) {
            if (message.getCode().equals(code)) {
                return message;
            }
        }
        return null;
    }

    public String getCode() {
        return code;
    }

    public MessageCategory getCategory() {
        return category;
    }

    public String getDescription() {
        return description;
    }

    public String getDescriptionDetail() {
        return descriptionDetail;
    }
}
