/*
    System: BlueTruth Outstation
    Language/Build: MS VC 2008 / Linux GCC 4.2+
    Modification History:

    Date        Who     SCJS No     Remarks
    31/05/2013  RG      001         V1.00 First Issue  
*/

#ifndef _GENERIC_ERROR_DIALOG_H_
#define _GENERIC_ERROR_DIALOG_H_

//!
//! @file
//! Subclass of ErrorDialog, which is generated by wxFormBuilder.
//!

#include "wxFormBuilderClasses.h"
#include "ierrordialog.h"
#include "keypresshandler.h"

#include <vector>

namespace View
{

class ErrorDialogTableIconRenderer : public wxGridCellStringRenderer
{
public:
    ErrorDialogTableIconRenderer();
    virtual ~ErrorDialogTableIconRenderer();

    virtual void Draw(wxGrid& grid,
                      wxGridCellAttr& attr,
                      wxDC& dc,
                      const wxRect& rect,
                      int row, int col,
                      bool isSelected);

    // get the preferred size of the cell for its contents
    virtual wxSize GetBestSize(wxGrid& grid,
                               wxGridCellAttr& attr,
                               wxDC& dc,
                               int row, int col);

    // create a new object which is the copy of this one
    virtual wxGridCellRenderer *Clone() const;

    static const wxString WARNING_ICON_FLAG;
    static const wxString ERROR_ICON_FLAG;
private:
    ErrorDialogTableIconRenderer(const ErrorDialogTableIconRenderer &rhs);
    ErrorDialogTableIconRenderer &operator =(const ErrorDialogTableIconRenderer &rhs);

    wxBitmap m_errorBitmap;
    wxBitmap m_warningBitmap;
};

class GenericErrorDialog : public IErrorDialog, public ErrorDialog, public KeyPressHandler
{
public:
    //! Constructor
    explicit GenericErrorDialog(wxWindow* parent );

    //! Destructor
    virtual ~GenericErrorDialog();

    void addErrorLog( const wxString &logMessage );

    void addWarningLog( const wxString &logMessage );

    //! display error
    virtual void displayError(const char* error);
    virtual void displayFatalError(const char* error);
    virtual void displayWarning(const char* warning);

private:
    //! default constructor. Not implemented
    GenericErrorDialog();
    //! copy constructor. Not implemented
    GenericErrorDialog(const GenericErrorDialog& rhs);
    //! copy assignment operator. Not implemented
    GenericErrorDialog& operator=(const GenericErrorDialog& rhs);

    virtual bool onKeyPressed(const wxKeyEvent& ev);

    // Handlers for ErrorDialog events.
    virtual void onInit(wxInitDialogEvent& ev);
    virtual void onClose( wxCloseEvent& ev );
    virtual void onClickOk( wxCommandEvent& event );
    virtual void onClickMore( wxCommandEvent& event );
    virtual void onIdle( wxIdleEvent& event );

    void showSingleMessage();
    void showMultipleMessage();
    void deleteAllRows();

    bool m_showingMore;
    wxBitmap m_errorBitmap;
    wxBitmap m_warningBitmap;

    wxMutex m_logMutex;

    std::vector<wxString> m_warningLogsToAdd;
    std::vector<wxString> m_errorLogsToAdd;

    void addLog( bool isError, const wxString &logMessage );

    void addPendingLogsToTable();
    void addPendingLog( bool isFirst, bool isError, const wxString &logMessage );

    size_t m_biggestStringLength;

};

} //namespace

#endif // _GENERIC_ERROR_DIALOG_H_
