/*
    System: BlueTruth Outstation
    Language/Build: MS VC 2008 / Linux GCC 4.2+
    Description: 
    Modification History:

    Date        Who     SCJS No     Remarks
    31/05/2013  RG      001         V1.00 First Issue  
*/

#ifndef _OUTSTATION_ABOUT_DIALOG_
#define _OUTSTATION_ABOUT_DIALOG_

//!
//! @file
//! Subclass of AboutDialog, which is generated by wxFormBuilder.
//!

#include "wxFormBuilderClasses.h"
#include "keypresshandler.h"


namespace View
{

class OutStationAboutDialog : public AboutDialog, public KeyPressHandler
{
public:
    //! Constructor
    explicit OutStationAboutDialog(wxWindow* pParent);

    //! Destructor
    virtual ~OutStationAboutDialog();

private:
    //! default constructor. Not implemented
    OutStationAboutDialog();
    //! copy constructor. Not implemented
    OutStationAboutDialog(const OutStationAboutDialog& rhs);
    //! copy assignment operator. Not implemented
    OutStationAboutDialog& operator=(const OutStationAboutDialog& rhs);

    virtual bool onKeyPressed(const wxKeyEvent& ev);

    // Handlers for AboutDialog events.
    virtual void onInit(wxInitDialogEvent& ev);
    virtual void onClose( wxCloseEvent& ev );
    virtual void onOkClick( wxCommandEvent& ev );
};

}

#endif // _OUTSTATION_ABOUT_DIALOG_
