\set ON_ERROR_STOP on
\i lib/SettingsStartUp.sql
\i lib/CheckServerAndDeleteData.sql
\i lib/ConfigurationAndDetections.sql
\i tests/ReportIndependence.sql
\i tests/Mode0.sql
\i tests/Mode1.sql
\i tests/Mode2.sql
\i tests/Mode3.sql
\i tests/PastDetection.sql
\i tests/ModeChange.sql
\i tests/FirstSeenTimestampTolerance0.sql
\i tests/FirstSeenTimestampTolerance1.sql
\i tests/FirstSeenTimestampTolerance2.sql
\i tests/FirstSeenTimestampTolerance3.sql
\i tests/Version3AndVersion4Detections1.sql
\i tests/Version3AndVersion4Detections2.sql
\i tests/Version3AndVersion4Detections3.sql
\i tests/Version3AndVersion4Detections4.sql
\i tests/Version3AndVersion4Detections5.sql
\i tests/SilentDetectorStatus.sql
\i tests/StatisticReportDeviceAddressLastTime.sql
\i tests/StatusReport.sql
\i lib/DefaultDetectorsConfiguration.sql
\i tests/DefaultConfiguration.sql
\i tests/DefaultConfigurationSpecifingUrlValues.sql
\i tests/SpecifyingAllValues.sql
